//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class contenuti_dettagli
    {
        public long id { get; set; }
        public System.DateTime data_rilascio { get; set; }
        public string dettagli { get; set; }
        public string libro { get; set; }
        public string consigliato { get; set; }
        public string recensione { get; set; }
    }
}
