//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datatypes.netebook
{
    using System;
    using System.Collections.Generic;
    
    public partial class contenuti
    {
        public long id { get; set; }
        public string titolo { get; set; }
        public double prezzo { get; set; }
        public Nullable<long> id_genere { get; set; }
        public Nullable<long> anno { get; set; }
        public Nullable<sbyte> attivo { get; set; }
        public string tipo { get; set; }
        public long id_major { get; set; }
        public string codice_prodotto { get; set; }
        public string codice_traccia { get; set; }
        public byte has_preview { get; set; }
        public byte has_img { get; set; }
        public byte has_drm { get; set; }
        public string codicemw { get; set; }
        public byte vendibile { get; set; }
        public long num_traccia { get; set; }
        public long num_volume { get; set; }
        public System.DateTime data_inserimento { get; set; }
        public string codice_prezzo_major { get; set; }
        public string artista { get; set; }
        public long rifalbum { get; set; }
        public long brani { get; set; }
        public string versione { get; set; }
        public long durata { get; set; }
        public string generi { get; set; }
        public Nullable<decimal> voto { get; set; }
        public Nullable<int> num_voti { get; set; }
        public string isbn { get; set; }
        public string pagine { get; set; }
        public Nullable<int> editato_manualmente { get; set; }
        public Nullable<System.DateTime> data_inizio_vendibilita { get; set; }
        public Nullable<System.DateTime> data_fine_vendibilita { get; set; }
        public string titolo_search { get; set; }
        public string artista_search { get; set; }
        public string editore { get; set; }
        public string linktowebtv { get; set; }
        public string preview_url { get; set; }
        public string filesize { get; set; }
        public string id_editore_per_previewurl { get; set; }
    }
}
