//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datatypes.netebook
{
    using System;
    using System.Collections.Generic;
    
    public partial class contenuti_dettagli
    {
        public long id { get; set; }
        public string upc { get; set; }
        public string isrc { get; set; }
        public string titolo { get; set; }
        public string versione { get; set; }
        public string tipologia { get; set; }
        public string album { get; set; }
        public string interprete { get; set; }
        public string compositore { get; set; }
        public string genere { get; set; }
        public System.DateTime data_rilascio { get; set; }
        public long brani { get; set; }
        public long durata { get; set; }
        public long dimensione { get; set; }
        public string distributore { get; set; }
        public string etichetta { get; set; }
        public string copyright { get; set; }
        public string formato { get; set; }
        public string bitrate { get; set; }
        public long numero { get; set; }
        public string dettagli { get; set; }
        public string credits { get; set; }
        public string durata_string { get; set; }
    }
}
